### ISSUE TITLE
Absolute position on infinite scroll nodes breaks table flow

### ISSUE THREAD

**Issue by deanpeterson** [GoogleChrome/ui-element-samples#79]
I am trying to use the infinite scroll tutorial to allow efficient scrolling on a matrix widget I wrote. However, it uses absolute positioning on the infinite scrolling nodes it creates. My nodes are table rows and columns. That takes all of the cells out of table flow. Is there an easy way to modify the infinite scroller to calculate the layout without absolutely positioning nodes? I see the section in the post about using absolute positioning to stay scrolling at 60 fps, however, I cannot make absolute positioning work for me. Could you possibly give me some hints on how to modify the layout calculations to work without it?

**Comment by surma** [comment]
As I already replied on Twitter, tables are very special and just transforming/positioning the rows won’t get you there.

My suggestion is to either switch to CSS Grid or adapt the solution to do the following:

Absolutely position the entire table, so that a couple of excess rows are above and below the viewport. Scroll normally and when the end of the table comes too close to the viewport, reshuffle the rows from the other end to the table and reposition the entire table so that the reshuffling is not visible.

Hope that helps :)
