### ISSUE TITLE
stream-progress: _percentage NaN

### ISSUE THREAD

**Issue by johnthad** [GoogleChrome/ui-element-samples#86]
If I run `stream-progress` with `simplehttp2server` v3.1.2, it fails with
```
dial.js:47 Uncaught (in promise) Error: Percentage must be a number between 0 and 1.
    at HTMLElement.set percentage [as percentage] (dial.js:47)
    at fetch.then (stream.js:94)
    at <anonymous>
```
A closer look tells me that `Number.isNaN(_percentage)` is `true`.

However if I run `stream-progress` with `python -m SimpleHTTPServer` it works as it did in the video.

I'm running on a MacBook with MacOS 10.11.6 and Chrome Canary 60.0.3105.0.

**Comment by surma** [comment]
I can't check it right now, but that's probably because SH2S has GZIP-on-the-fly enabled and therefore doesn't send a `Content-Length` header. 

One solution is to craft a `HEAD` request to get the uncompressed file size and use that as an estimation, or use a server that pre-compresses and sends the header.
